# Mitigate and emission cuts?

## Question: What measures can be taken by urban centers to mitigate and cut down on their emissions?

## Query result: Climate Change 2022: Mitigation of Climate Change. Chapter 08 : Urban Systems and Other Settlements

Chapter 8 Urban Systems and Other Settlements. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the 6th Assessment Report of the IPCC

URL: [https://www.ipcc.ch/report/ar6/wg3/](https://www.ipcc.ch/report/ar6/wg3/)

*This chapter should be cited as : Lwasa, S., K.C. Seto, X. Bai, H. Blanco, K.R. Gurney, Ş. Kılkış, O. Lucon, J. Murakami, J. Pan, A. Sharifi, Y. Yamagata, 2022: Urban systems and other settlements. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [P.R. Shukla, J. Skea, R. Slade, A. Al Khourdajie, R. van Diemen, D. McCollum, M. Pathak, S. Some, P. Vyas, R. Fradera, M. Belkacemi, A. Hasija, G. Lisboa, S. Luz, J. Malley, (eds.)]. Cambridge University Press, Cambridge, UK and New York, NY, USA.*

---

## Content:

### Chapter 08 : Urban Systems and Other Settlements 

#### Executive Summary

Although urbanisation is a global trend often associated with increased incomes and higher consumption, the growing concentration of people and activities is an opportunity to increase resource efficiency and decarbonise at scale (very high confidence). The same urbanisation level can have large variations in per capita urban carbon emissions. For most regions, per capita urban emissions are lower than per capita national emissions. {8.1.4, 8.3.3, 8.4, Box 8.1} 

Most future urban population growth will occur in developing countries, where per capita emissions are currently low but expected to increase with the construction and use of new infrastructure and the built environment, and changes in incomes and lifestyles (very high confidence).  The drivers of urban greenhouse gas (GHG) emissions are complex and include an interplay of population size, income, state of urbanisation, and how cities are laid out (i.e. urban form). How new cities and towns are designed, constructed, managed, and powered will lock-in behaviour, lifestyles, and future urban GHG emissions. Low-emission urbanisation can improve well-being while minimising impact on GHG emissions, but there is risk that urbanisation can lead to increased global GHG emissions through increased emissions outside the city’s boundaries. {8.1.4, 8.3, Box 8.1, 8.4, 8.6}

The urban share of global GHG emissions (including carbon dioxide (CO2) and methane (CH4)) is substantive and continues to increase (high confidence). In 2015, urban emissions were estimated to be 25 GtCO2-eq (about 62% of the global share) and in 2020, 29 GtCO2-eq (67–72% of the global share).1 About 100 of the highest emitting urban areas account for approximately 18% of the global carbon footprint. {8.1.6, 8.3.3}

The urban share of regional GHG emissions increased between 2000 and 2015, with much inter-region variation in the magnitude of the increase (high confidence). Globally, the urban share of national emissions increased 6 percentage points, from 56% in 2000 to 62% in 2015. For 2000 to 2015, the urban emissions share across AR6 WGIII regions increased from 28% to 38% in Africa, from 46% to 54% in Asia and Pacific, from 62% to 72% in Developed Countries, from 57% to 62% in Eastern Europe and West-Central Asia, from 55% to 66% in Latin America and Caribbean, and from 68% to 69% in the Middle East. {8.1.6, 8.3.3} 

Per capita urban GHG emissions increased between 2000 and 2015, with cities in the Developed Countries region producing nearly seven times more per capita than the lowest emitting region (medium confidence). From 2000 to 2015, global urban GHG emissions per capita increased from 5.5 to 6.2 tCO2-eq per person (an  increase of 11.8%); Africa increased from 1.3 to 1.5 tCO2-eq per person (22.6%); Asia and Pacific increased from 3.0 to 5.1 tCO2-eq per person (71.7%); Eastern Europe and West-Central Asia increased from 6.9 to 9.8 tCO2-eq per person (40.9%); Latin America and Caribbean increased from 2.7 to 3.7 tCO2-eq per person (40.4%); and Middle East increased from 7.4 to 9.6 tCO2-eq per person (30.1%). Albeit starting from the highest level, Developed Countries had a decline of 11.4 to 10.7 tCO2-eq per person (–6.5%). {8.3.3}

The global share of future urban GHG emissions is expected to increase through 2050, with moderate to low mitigation efforts, due to growth trends in population, urban land expansion, and infrastructure and service demands, but the extent of the increase depends on the scenario and the scale and timing of urban mitigation action (medium confidence). In modelled scenarios, global consumption-based urban CO2 and CH4 emissions are projected to rise from 29 GtCO2-eq in 2020 to 34 GtCO2-eq in 2050 with moderate mitigation efforts (intermediate GHG emissions, SSP2–4.5), and up to 40 GtCO2-eq in 2050 with low mitigation efforts (high GHG emissions, SSP3–7.0). 

Urban land areas could triple between 2015 and 2050, with significant implications for future carbon lock-in. There is a  large range in the forecasts of urban land expansion across scenarios and models, which highlights an opportunity to shape future urban development towards low- or net-zero GHG emissions and minimise the loss of carbon stocks and sequestration in the agriculture, forestry and other land use (AFOLU) sector due to urban land conversion (medium confidence). 

The construction of new, and upgrading of, existing urban infrastructure through 2030 will result in significant emissions (very high confidence). The construction of new and upgrading of existing urban infrastructure using conventional practices and technologies can result in significant committed CO2 emissions, ranging from 8.5 GtCO2 to 14 GtCO2 annually up to 2030 and more than double annual resource requirements for raw materials to about 90 billion tonnes per year by 2050, up from 40 billion tonnes in 2010 (medium evidence, high agreement). {8.4.1, 8.6} 

Cities can only achieve net-zero GHG emissions through deep decarbonisation and systemic transformation (very high confidence). Three broad mitigation strategies have been found to be effective in reducing emissions when implemented concurrently: (i) reducing or changing urban energy and material use towards more sustainable production and consumption across all sectors, including through compact and efficient urban forms and supporting infrastructure; (ii) electrification and switching to net-zero-emissions resources; and (iii) enhancing carbon uptake and storage in the urban environment (high evidence, high agreement). Given the regional and global reach of urban supply chains, cities can achieve net-zero emissions only if emissions are reduced within and outside of their administrative boundaries. {8.1.6, 8.3.4, 8.4, 8.6} 

Packages of mitigation policies that implement multiple urbanscale interventions can have cascading effects across sectors, reduce GHG emissions outside of a  city’s administrative boundaries, and reduce more emissions than the net sum of individual interventions, particularly if multiple scales of governance are included (high confidence). Cities have the ability to implement policy packages across sectors using an urban systems approach, especially those that affect key infrastructure based on spatial planning, electrification of the urban energy system, and urban green and blue infrastructure. The institutional capacity of cities to develop, coordinate, and integrate sectoral mitigation strategies within their jurisdiction varies by context, particularly those related to governance, the regulatory system, and budgetary control. {8.4, 8.5, 8.6} 

Integrated spatial planning to achieve compact and resourceefficient urban growth through co-location of higher residential and job densities, mixed land use, and transit-oriented development (TOD) could reduce GHG emissions between 23% and 26% by 2050 compared to the business-as-usual scenario (robust evidence, high agreement, very high confidence). Compact cities with shortened distances between housing and jobs, and interventions that support a modal shift away from private motor vehicles towards walking, cycling, and low-emissions shared and public transportation, passive energy comfort in buildings, and urban green infrastructure can deliver significant public health benefits and have lower GHG emissions. {8.2, 8.3.4, 8.4, 8.6}

Urban green and blue infrastructure can mitigate climate change through carbon sequestration, avoided emissions, and reduced energy use while offering multiple co-benefits (robust evidence, high agreement). Urban green and blue infrastructure, including urban forests and street trees, permeable surfaces, and green roofs3 offer potential to mitigate climate change directly through sequestering and storing carbon, and indirectly by inducing a cooling effect that reduces energy demand and reducing energy use for water treatment. Global urban trees store approximately 7.4 billion tonnes of carbon, and sequester approximately 217 million tonnes of carbon annually, although urban tree carbon storage and sequestration are highly dependent on biome. Among the multiple co-benefits of green and blue infrastructure are reducing the urban heat island (UHI) effect and heat stress, reducing stormwater runoff, improving air quality, and improving mental and physical health of urban dwellers. {8.2, 8.4.4}

With over 880 million people living in informal settlements, there are opportunities to harness and enable informal practices and institutions in cities related to housing, waste, energy, water, and sanitation to reduce resource use and mitigate climate change (low evidence, medium agreement). The upgrading of informal settlements and inadequate housing to improve resilience and well-being offers a chance to create a lowcarbon transition. However, there is limited quantifiable data on these practices and their cumulative impacts on GHG emissions. {8.1.4, 8.2.2, Cross-Working Group Box 2, 8.3.2, 8.4, 8.6, 8.7}





