# Q2. Renewable energy?

## Question: What role do renewable energy sources play in city climate plans?

## Query result: Box 6.8 | 100% Renewables in Net-zero Energy Systems (Page 675-676)

Chapter 6 Energy Systems. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the 6th Assessment Report of the IPCC

URL: [https://www.ipcc.ch/report/ar6/wg3/](https://www.ipcc.ch/report/ar6/wg3/)

*Cite: Clarke, L., Y.-M. Wei, A. De La Vega Navarro, A. Garg, A.N. Hahmann, S. Khennas, I.M.L. Azevedo, A. Löschel, A.K. Singh, L. Steg, G. Strbac, K. Wada, 2022: Energy Systems. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [P.R. Shukla, J. Skea, R. Slade, A. Al Khourdajie, R. van Diemen, D. McCollum, M. Pathak, S. Some, P. Vyas, R. Fradera, M. Belkacemi, A. Hasija, G. Lisboa, S. Luz, J. Malley, (eds.)]. Cambridge University Press, Cambridge, UK and New York, NY, USA. doi: 10.1017/9781009157926.008.*

---

## Content:

### Box 6.8 | 100% Renewables in Net-zero Energy Systems

The decreasing cost and increasing performance of renewable energy has generated interest in the feasibility of providing nearly all energy
services with renewables. Renewable energy includes wind power, solar power, hydroelectric power, bioenergy, geothermal energy, tidal
power, and ocean power. There are two primary frames around which 100% renewable energy systems are discussed: 100% renewable
electricity systems and 100% renewable energy systems, considering not only electricity but all aspects of the energy system.

It is technically feasible to use very high renewable shares (e.g., above 75% of annual regional generation) to meet hourly electricity
demand under a range of conditions, especially when VRE options, notably wind and solar, are complemented by other resources (high
confidence). There are currently many grids with high renewable shares and large anticipated roles for VRE sources, in particular wind
and solar (Section 6.4), in future low-carbon electricity systems. An increasingly large set of studies examines the feasibility of high
renewable penetration and economic drivers under different policy, technology, and market scenarios (Cochran et al. 2014; Deason
2018; Jenkins et al. 2018b; Bistline et al. 2019; Hansen et al. 2019; Dowling et al. 2020; Blanford et al. 2021; Denholm et al. 2021).
High wind and solar penetration involves technical and economic challenges due to their unique characteristics such as spatial and
temporal variability, short- and long-term uncertainty, and non-synchronous generation (Cole et al. 2017). These challenges become
increasingly important as renewable shares approach 100% (Sections 6.6.2.2 and 6.4.3).

There are many balancing options in systems with very high renewables (Milligan et al. 2015; Jenkins et al. 2018b; Mai et al. 2018;
Bistline 2021a; Denholm et al. 2021).

 - Energy storage. Energy storage technologies like batteries, pumped hydro, and hydrogen can provide a range of system
services (Balducci et al. 2018; Bistline et al. 2020a) (Section 6.4.4). Lithium-ion batteries have received attention as costs fall and
installations increase, but very high renewable shares typically entail either dispatchable generation or long-duration storage in
addition to short-duration options (Jenkins et al. 2018b; Arbabzadeh et al. 2019; Schill 2020). Energy storage technologies are
part of a broad set of options (including synchronous condensers, demand-side measures, and even inverter-based technologies
themselves) for providing grid services (Castillo and Gayme 2014; EPRI 2019a).
 - Transmission and trade. To balance differences in resource availability, high renewable systems will very likely entail investments
in transmission capacity (Mai et al. 2014; Macdonald et al. 2016; Pleßmann and Blechinger 2017; Zappa et al. 2019) (Section 6.4.5)
and changes in trade (Abrell and Rausch 2016; Bistline et al. 2019). These increases will likely be accompanied by expanded
balancing regions to take advantage of geographical smoothing.
 - Dispatchable (‘on-demand’) generation. Dispatchable generation could include flexible fossil units or low-carbon fuels such
as hydrogen with lower minimum load levels (Denholm et al. 2018; Bistline 2019), renewables like hydropower, geothermal, or
biomass (Hirth 2016; Hansen et al. 2019), or flexible nuclear (Jenkins et al. 2018a). The composition depends on costs and other
policy goals, though in all cases, capacity factors are low for these resources (Mills et al. 2020).
 - Demand management: Many low-emitting and high-renewables systems also utilise increased load flexibility in the forms of
energy efficiency, demand response, and demand flexibility, utilising newly electrified end uses such as electric vehicles to shape
demand profiles to better match supply (Ameli et al. 2017; Hale 2017; Brown et al. 2018; Imelda et al. 2018a; Bistline 2021a).
• Sector coupling: Sector coupling includes increased end-use electrification and PtX electricity conversion pathways, which may
entail using electricity to create synthetic fuels such as hydrogen (Davis et al. 2018; Ueckerdt et al. 2021) (Sections 6.4.3, 6.4.,
6.4.5, 6.6.4.3, and 6.6.4.6).

Deployment of integration options depends on their relative costs and value, regulations, and electricity market design. There is
considerable uncertainty about future technology costs, performance, availability, scalability, and public acceptance (Kondziella and
Bruckner 2016; Bistline et al. 2019). Deploying balanced resources likely requires operational, market design, and other institutional
changes, as well as technological changes in some cases (Denholm et al. 2021; Cochran et al. 2014). Mixes will differ based on
resources, system size, flexibility, and whether grids are isolated or interconnected.

Although there are no technical upper bounds on renewable electricity penetration, the economic value of additional wind and
solar capacity typically decreases as their penetration rises, creating economic challenges at higher deployment levels (Hirth 2013;
Gowrisankaran et al. 2016; Cole et al. 2021; Denholm et al. 2021; Millstein et al. 2021). The integration options above, as well as changes
to market design, can mitigate these challenges but likely will not solve them, especially since these options can exhibit declining value
themselves (De Sisternes et al. 2016; Bistline 2017; Denholm and Mai 2019) and may be complements or substitutes to each other.

Energy systems that are 100% renewable (including all parts of the energy sector, and not only electricity generation) raise a range
of technological, regulatory, market, and operational challenges that make their competitiveness uncertain (high confidence).
These systems require decarbonising all electricity, using this zero-carbon electricity broadly, and then utilising zero-carbon energy
carriers for all end uses not served by electricity, for example, air travel, long-distance transport, and high-temperature process heat.
Broader questions emerge regarding the attractiveness of supplying all energy, and not just electricity, with renewables (Figure 6.22).
Integrated assessment and energy systems research suggest large roles for renewables, but energy and electricity shares are far from
100%, even with stringent emissions reductions targets and optimistic assumptions about future cost reductions (Bauer et al. 2018;
Bistline et al. 2018; Jenkins et al. 2018b; Huntington et al. 2020) (Section 6.7.1). Scenarios with 100% renewable energy systems
are an emerging subset in the decarbonisation literature, especially at regional levels (Hansen et al. 2019; Denholm et al. 2021).
Many 100% renewables studies focus more heavily on electrification for decarbonising end uses, and include less biofuels and
hydrogen than the broader literature on deep decarbonisation (Bauer et al. 2018a). These studies typically assume a constrained set of
available technologies to demonstrate the technical feasibility of very high renewable systems and do not optimise to find least-cost,
technology-neutral decarbonisation pathways, and many 100% renewables studies focus on the electricity sector or a limited number
of sectors (Jenkins et al. 2018a; Hansen et al. 2019). In addition to renewables, studies broadly agree that including additional lowcarbon
options – including not only low-carbon electricity but also targeted use of fossil fuels with and without CCS (Section 6.6.2.1)
and alternative fuels for sectors that are difficult to electrify (Section 6.6.2.4) – can lower the cost of decarbonisation, even with very
high shares of renewables (Figure 6.22). However, there is disagreement about the magnitude of cost savings from larger portfolios,
which depend on context- and scenario-specific assumptions about technologies, markets, and policies.


