# Q3. Sustainable Transport Options?

## Question: How can cities promote sustainable transportation options in their climate action plans?  

## Query result: 10.7.4 Transport Modes Trajectories (Page 1104-1106)

Chapter 10 Transport. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the 6th Assessment Report of the IPCC

URL: [https://www.ipcc.ch/report/ar6/wg3/](https://www.ipcc.ch/report/ar6/wg3/)

*Cite: Jaramillo, P., S. Kahn Ribeiro, P. Newman, S. Dhar, O.E. Diemuodeke, T. Kajino, D.S. Lee, S.B. Nugroho, X. Ou, A. Hammer Strømman, J. Whitehead, 2022: Transport. In IPCC, 2022: Climate Change 2022: Mitigation of Climate Change. Contribution of Working Group III to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [P.R. Shukla, J. Skea, R. Slade, A. Al Khourdajie, R. van Diemen, D. McCollum, M. Pathak, S. Some, P. Vyas, R. Fradera, M. Belkacemi, A. Hasija, G. Lisboa, S. Luz, J. Malley, (eds.)]. Cambridge University Press, Cambridge, UK and New York, NY, USA. doi: 10.1017/9781009157926.012* 

---

## Content: 

### 10.7.4 Transport Modes Trajectories

![**Figure 10.19 | Transport activity trajectories for passenger and freight across different modes.** Global passenger (billion pkm per year) and freight (billion tkm per year) demand projections relative to a modelled year 2020 index. Results for IAM are for selected stabilisation temperatures by 2100. Also included are global transport models Reference and Policy scenarios. Data from the AR6 scenario database. Trajectories span the 5th to 95th percentiles across models, with a solid line indicating the median value across models.](images/Fig-10.19.PNG "Figure 10.19 | Transport activity trajectories for passenger and freight across different modes. Global passenger (billion pkm per year) and freight (billion tkm per year) demand projections relative to a modelled year 2020 index. Results for IAM are for selected stabilisation temperatures by 2100. Also included are global transport models Reference and Policy scenarios. Data from the AR6 scenario database. Trajectories span the 5th to 95th percentiles across models, with a solid line indicating the median value across models.")

Globally over the last century, shares of faster transport modes have
generally increased with increasing passenger travel demand (Schäfer
2017; Schafer and Victor 2000). For short- to medium-distance travel,
private cars have displaced public transit, particularly in OECD
countries, due to a variety of factors, including faster travel times in
many circumstances (Liao et al. 2020); consumers increasingly valuing
time and convenience with GDP growth; and broader transport
policies, such as provision of road versus public transit infrastructure
(Mattioli et al. 2020). For long-distance travel, travel via aviation for
leisure and business has increased (Lee et al. 2021). These trends do
not hold in all countries and cities, as many now have rail transit
that is faster than driving (Newman et al. 2015). For instance,
public transport demand rose from 1990 through to 2016 in France,
Denmark, and Finland (eurostat 2019). In general, smaller and denser
countries and cities with higher or increasing urbanisation rates tend
to have greater success in increasing public transport share. However,
other factors, like privatisation of public transit (Bayliss and Mattioli
2018) and urban form (ITF 2021), also play a role. Different transport
modes can provide passenger and freight services, affecting the
emissions trajectories for the sector.

Figure 10.19 shows activity trajectories for freight and passenger
transport through 2100 relative to a modelled year 2020 across
different modes, based on the AR6 database for IAMs and global
transport models. Globally, climate scenarios from IAMs, and policy
and reference scenarios from global transport models, indicate
increasing demand for freight and passenger transport via most modes
through 2100 (Yeh et al. 2017; Mulholland et al. 2018; Zhang et al.
2018; Khalili et al. 2019). Road passenger transport exhibits a similar
increase (roughly tripling) through 2100 across scenarios. For road passenger transport, scenarios that limit or return warming
to 1.5°C during the 21st century (C1–C2) have a smaller increase
from modelled 2020 levels (median increase of 2.4 times modelled
2020 levels) than do scenarios with higher warming levels (C3–C8)
(median increase of 2.7–2.8 times modelled 2020 levels). There are
similar patterns for passenger road transport via light-duty vehicle,
for which median increases from modelled 2020 levels are smaller
for C1–C2 (3 times larger) than for C3–C5 (3.1 times larger) or C6–C7
(3.2 times larger). Passenger transport via aviation exhibits a 2.2
times median increase relative to modelled 2020 levels under C1–C2
and C3–C5 scenarios but exhibits a 6.2 times increase under C6–C8.
The only passenger travel mode that exhibits a decline in its median
value through 2100 according to IAMs is walking/bicycling, in C3–
C5 and C6–C8 scenarios. However, in C1–C2 scenarios, walking/
bicycling increases by 1.4 times relative to modelled 2020 levels.
At the 5th percentile of IAM solutions (lower edge of bands in
Figure 10.19), buses and walking/bicycling for passenger travel both
exhibit significant declines.

For freight, Figure 10.19 shows that the largest growth occurs in
transport via road (Mulholland et al. 2018). By 2100, global transport
models suggest a roughly four-fold increase in median-heavy-duty
trucking levels relative to modelled 2020 levels, while IAMs suggest
a two- to four-fold increase in freight transport by road by 2100.
Notably, the 95th percentile of IAM solutions see road transport
by up to 4.7 times through 2100 relative to modelled 2020 levels,
regardless of warming level. Other freight transport modes – aviation,
international shipping, navigation, and railways – exhibit less growth
than road transport. In scenarios that limit or return warming to
1.5°C (>50%) during the 21st century (C1–C2), navigation and
rail transport remain largely unchanged and international shipping
roughly doubles by 2100. Scenarios with higher warming (i.e., moving
from C1–C2 to C6–C8) generally lead to more freight by rail and less
freight by international shipping.

Relative to global trajectories, upper-income regions – including
North America, Europe, and the Pacific OECD – generally see less
growth in passenger road via light-duty vehicle and passenger
aviation, given more saturated demand for both. Other regions like
China exhibit similar modal trends as the global average, whereas
regions such as the African continent and Indian subcontinent exhibit
significantly larger shifts, proportionally, in modal transport than the
globe. In particular, the African continent represents the starkest
departure from global results. Freight and passenger transport modes
exhibit significantly greater growth across Africa than globally in all
available scenarios. Across Africa, median freight and passenger
transport via road from IAMs increases by 5 to 16 times and 4 to
28 times, respectively, across warming levels by 2100 relative
to modelled 2020 levels. Even C1 has considerable growth in Africa
via both modes (3 to 16 times increase for freight and 4 to 29 times
increase for passenger travel at 5th and 95th percentiles of IAM
solutions by 2100).

As noted in Section 10.2, commonly explored mitigation options
related to mode change include a shift to public transit, shared
mobility, and demand reductions through various means, including
improved urban form, teleconferences that replace passenger travel (Creutzig et al. 2018; Grubler et al. 2018; Wilson et al. 2019),
improved logistics efficiency, green logistics, and streamlined supply
chains for the freight sector (Mulholland et al. 2018). NDCs often
prioritise options like bus improvements and enhanced mobility that
yield pollution, congestion, and urban development co-benefits,
especially in medium- and lower-income countries (Fulton et al.
2017). Conversely, high-income countries, most of which have
saturated and entrenched private vehicle ownership, typically focus
more on technology options, such as electrification and fuel efficiency
standards (Gota et al. 2016). Available IAM and regional models are
limited in their ability to represent modal shift strategies. As a result,
mode shifts alone do not differentiate climate scenarios. While this
lack of representation is a limitation of the models, it is unlikely that
such interventions would completely negate the increases in demand
the models suggest. Therefore, transport via light-duty vehicle and
aviation, freight transport via road, and other modes will likely
continue to increase through to the end of the century. Consequently,
fuel and carbon efficiency and fuel energy and technology will
probably play crucial roles in differentiating climate scenarios, as
discussed in the following sub-sections.




